services:
  Pest\Drift\PHPUnit\MethodToPestTestRector: ~
  Pest\Drift\PHPUnit\TraitUsesToUsesRector: ~
  Pest\Drift\PHPUnit\SetUpToBeforeRector: ~
  Pest\Drift\PHPUnit\TearDownToAfterEachRector: ~
  Pest\Drift\PHPUnit\AfterClassToAfterAllRector: ~
  Pest\Drift\PHPUnit\BeforeClassToBeforeAllRector: ~
  Pest\Drift\PHPUnit\PhpDocGroupOnClassToFileScopeGroupRector: ~
  Pest\Drift\PHPUnit\DataProviderRector: ~
  Pest\Drift\PHPUnit\HelperMethodRector: ~
  Pest\Drift\PHPUnit\CustomTestCaseToUsesRector: ~

  Pest\Drift\PHPUnit\RemovePHPUnitClassRector: ~
  Pest\Drift\Pest\PestCollectingRector: ~


  Pest\Drift\PestCollector: ~
